In [ ]:
import numpy as np

def to_embedding(text):
  tokens = text.lower().split()

  vocab = sorted(set(tokens))
  word_idx = {word: idx for idx, word in enumerate(vocab)}

  # embedding matrix
  embedding_dim = 5
  embedding_matrix = np.random.randn(len(vocab), embedding_dim)

  # convert sentence into embedding
  sentence_embeddings = []

  for token in tokens:
      idx = word_idx[token]
      sentence_embeddings.append(embedding_matrix[idx])

  sentence_embeddings = np.array(sentence_embeddings)
  return sentence_embeddings

In [ ]:
embedding_vector = to_embedding("I love machine learning")
embedding_vector

array([[-1.2567213 , -1.96661889, -0.63256152,  1.14362838,  0.75667674],
       [ 0.49096321,  0.09447559,  1.06415389, -1.12701038, -1.13140432],
       [-0.47150916,  0.95631446, -1.11314464,  0.09879376, -0.69890422],
       [ 0.42577395,  0.19889883,  0.18322372, -0.02900213, -0.3516453 ]])

## Defining self-attention

In [ ]:
def softmax(x):
    exp = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp / np.sum(exp, axis=-1, keepdims=True)

In [ ]:
def initialize_weights(embedding_dim, d_k, d_v=None):
    if d_v is None:
        d_v = d_k

    w_Q = np.random.randn(embedding_dim, d_k)
    w_K = np.random.randn(embedding_dim, d_k)
    w_V = np.random.randn(embedding_dim, d_v)

    return w_Q, w_K, w_V

In [ ]:
def attention(embedding):
    # embedding: (seq_len, embedding_dim)
    embedding = np.asarray(embedding)
    w_Q, w_K, w_V = initialize_weights(embedding.shape[1], embedding.shape[1])

    # Generate Q, K, V
    Q = embedding @ w_Q
    K = embedding @ w_K
    V = embedding @ w_V

    # Compute Attention Scores
    seq_len = len(embedding)
    d_k = K.shape[1]
    scores = (Q @ K.T) / np.sqrt(d_k)

    # Softmax
    weights = softmax(scores)

    # Weighted Sum of Values
    output = weights @ V
    return output, weights, scores, Q, K, V

In [ ]:
output, weights, scores, Q, K, V = attention(embedding_vector)

In [ ]:
(Q[0] @ K[0]) / np.sqrt(K.shape[1])

np.float64(2.233511853049632)

In [ ]:
scores

array([[ 2.23351185, -1.74528907, -2.33143294, -1.44438417],
       [-0.26365688,  0.66315108, -1.05499401,  0.17446212],
       [ 3.51801496, -1.83005237, -1.51197912,  0.34078742],
       [-0.32175092, -0.13304712, -0.40150977,  0.07997614]])

In [ ]:
output

array([[-0.45412191, -1.40350573,  0.98600039, -5.74034139, -3.42991993],
       [ 0.37248141,  1.08589858,  1.27882355,  0.61135209, -0.78545319],
       [-0.463708  , -1.435477  ,  0.97776895, -5.7787611 , -3.4297775 ],
       [ 0.22464313,  0.22618179,  0.31638976, -0.02104486, -0.45685288]])

In [ ]:
weights

array([[0.94841152, 0.01774294, 0.00987339, 0.02397214],
       [0.1808495 , 0.45690394, 0.08196793, 0.28027863],
       [0.94967006, 0.0045179 , 0.00620975, 0.0396023 ],
       [0.21619632, 0.26109666, 0.19962249, 0.32308452]])

## testing

In [ ]:
first_vec = to_embedding("Money bank grows")
sec_vec = to_embedding("River bank flows")

In [ ]:
first_vec_output, *rest1 = attention(first_vec)
sec_vec_output, *rest2 = attention(sec_vec)

In [ ]:
# compare both bank's contextual embedding
first_vec_output, sec_vec_output

(array([[ 2.11119057, -1.93415584, -2.28196297,  1.63976146,  1.76264958],
        [ 0.2962158 , -0.0319133 ,  1.60227625, -0.80621109,  0.03507162],
        [ 2.22852933, -1.93629323, -2.11362801,  1.49453014,  1.84064687]]),
 array([[ 1.40036609,  1.50164749, -2.17344802,  1.43749964,  2.68317049],
        [ 0.50564653,  3.40351113,  0.95035881,  1.22656629,  0.129184  ],
        [ 0.74906111,  2.8975452 ,  0.11557685,  1.29377457,  0.8232133 ]]))

## Conclusion:
   - After comparing two same words embedding we can ensure that both same looking words can have different embedding on the basis of context.