# Basic neural network with 5 weights and 1 bias.

In [5]:
import torch
import torch.nn as nn

class myNN(nn.Module):
  def __init__(self, num_features):
    # define neual network architecture
    super().__init__()    # invoke parent class's constructor
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    output = self.linear(features)
    return self.sigmoid(output)

In [6]:
features = torch.rand(10, 5)
model = myNN(5)
model(features)

tensor([[0.4911],
        [0.5202],
        [0.4698],
        [0.5320],
        [0.4956],
        [0.4564],
        [0.5165],
        [0.4998],
        [0.5693],
        [0.4618]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.1162,  0.0261, -0.1709,  0.2194,  0.2325]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([-0.1217], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
myNN                                     [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural network with hidden layers.

In [13]:
class Neural_Network(nn.Module):
  def __init__(self, num_features):
    # define neual network architecture
    super().__init__()    # invoke parent class's constructor
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    output = self.linear1(features)
    output = self.relu(output)
    output = self.linear2(output)
    output = self.sigmoid(output)

    return output;

In [14]:
features = torch.rand(10, 5)

md = Neural_Network(5)
md(features)

tensor([[0.6356],
        [0.6418],
        [0.6484],
        [0.6472],
        [0.6554],
        [0.6356],
        [0.6356],
        [0.6420],
        [0.6454],
        [0.6480]], grad_fn=<SigmoidBackward0>)

In [15]:
md.linear1.weight

Parameter containing:
tensor([[ 0.1787,  0.2980, -0.3641,  0.0729,  0.2737],
        [ 0.0133,  0.3598, -0.2882, -0.3384,  0.0135],
        [-0.2344, -0.0036, -0.1569, -0.3621, -0.4325]], requires_grad=True)

In [16]:
md.linear2.weight

Parameter containing:
tensor([[ 0.5188,  0.2283, -0.5758]], requires_grad=True)

In [17]:
from torchinfo import summary

summary(md, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Neural_Network                           [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequantial NN module.

In [20]:
class Sq_NN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    output = self.network(features)
    return output;

In [24]:
newMD = Sq_NN(5)
newMD(features)

tensor([[0.4278],
        [0.4022],
        [0.4073],
        [0.4269],
        [0.4070],
        [0.4064],
        [0.4055],
        [0.4094],
        [0.4021],
        [0.4192]], grad_fn=<SigmoidBackward0>)