In [1]:
import torch

In [ ]:
x = torch.tensor(3, dtype=torch.float64, requires_grad=True)

In [ ]:
y = x**2

In [ ]:
y

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6., dtype=torch.float64)

# Operation on nested functions

In [ ]:
# manually
import math

# function that derived manually
def f(x):
  return 2 * x * math.cos(x**2)

In [ ]:
f(3)

-5.466781571308061

In [ ]:
y = x**2
z = torch.sin(y)

In [ ]:
x, y, z

(tensor(3., dtype=torch.float64, requires_grad=True),
 tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>),
 tensor(0.4121, dtype=torch.float64, grad_fn=<SinBackward0>))

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668, dtype=torch.float64)

# Calculating gradient of loss functions.

In [3]:
# manual way

x = torch.tensor(6.7)   # input feature
y = torch.tensor(0.0)   # True label (target /  binary (0/1))

w = torch.tensor(1.0)   # weight
b = torch.tensor(0.0)   # bias

In [4]:
# function to get loss (binary cross-entropy loss)
def loss(prediction, target):
  epsilon = 1e-8  # to prevent log(0)
  prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
  return - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction));


In [5]:
# Forward pass
z = w * x + b
y_pred = torch.sigmoid(z)
bin_loss = loss(y_pred, y)

In [8]:
bin_loss

tensor(6.7012)

In [10]:
# Derivatives / Backward pass / Backpropagation
dl_dypred = (y_pred - y) / (y_pred * (1 - y_pred))
dypred_dz = y_pred * (1 - y_pred)
dz_dw = x
dz_db = 1

dl_dw = dl_dypred * dypred_dz * dz_dw
dl_db = dl_dypred * dypred_dz * dz_db

In [11]:
print("Manual dw: ", dl_dw)
print("Manual db: ", dl_db)

Manual dw:  tensor(6.6918)
Manual db:  tensor(0.9988)


# Mentos zindagi.

In [14]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

z = w * x + b
y_pred = torch.sigmoid(z)
bin_loss = loss(y_pred, y)

In [15]:
z, y_pred, bin_loss

(tensor(6.7000, grad_fn=<AddBackward0>),
 tensor(0.9988, grad_fn=<SigmoidBackward0>),
 tensor(6.7012, grad_fn=<NegBackward0>))

In [16]:
# Backward pass
bin_loss.backward()

In [23]:
print("AutoGrad dw: ", w.grad)
print("AutoGrad db: ", b.grad)

AutoGrad dw:  tensor(6.6918)
AutoGrad db:  tensor(0.9988)


In [29]:
# multi features computation / operation on vectors
x = torch.tensor([1, 2, 3], dtype=torch.float64, requires_grad=True)
y = (x**2).mean()

In [30]:
y.backward()

In [31]:
x.grad

tensor([0.6667, 1.3333, 2.0000], dtype=torch.float64)

In [28]:
# diable gradient tracking
# 1:
x.requires_grad_(False)

tensor([1., 2., 3.], dtype=torch.float64)

In [32]:
# 2:
y = x.detach() ** 2

In [34]:
y

tensor([1., 4., 9.], dtype=torch.float64)

In [35]:
# 3:
x = torch.tensor(2.0, requires_grad=True)
with torch.no_grad():
  y = x**2

In [36]:
y

tensor(4.)