In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [5]:
torch.cuda.is_available()
torch.cuda.device_count(), torch.cuda.get_device_name(0)


(1, 'Tesla T4')

In [7]:
# tensors creation
tensor = torch.empty(2, 3) # creates empty matrics with memory allocation of given size of matrcs
type(tensor)

torch.Tensor

In [12]:
zeroMat = torch.zeros(2, 3) # will create matrics of initialized value - 0
onesMat = torch.ones(2, 3) # will create matrics of initialized value - 1
randMat = torch.rand(2, 3) # will create matrics of initialized value - random
print(zeroMat)
print(onesMat)
print(randMat)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7152, 0.5903, 0.2655],
        [0.2800, 0.1681, 0.9113]])


In [13]:
# user-defined tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
# more ways
print(torch.arange(1, 10, 1))   # create tensor in range of 1 - 10 with 1 of jumps
print(torch.linspace(1, 10, 5))  # create tensor in range of 1 - 10 with 5 elements
print(torch.logspace(1, 10, 5))
print(torch.eye(5))   # create matrics of 5x5 size

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [32]:
# if i wanna create a same size tensor i had with filled value of zero or ones.
print(torch.empty_like(tensor))
print(torch.zeros_like(tensor))
print(torch.ones_like(tensor))
print(torch.rand_like(tensor.to(torch.float64)))

tensor([[         179106736,          282041248,                 80],
        [                64,          281898409, 288230376151711744]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.7930, 0.6427, 0.8506],
        [0.6681, 0.4929, 0.7886]], dtype=torch.float64)


In [27]:
# assign dtypes with tesnor creation
myTensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
print(myTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [38]:
newTensor = torch.tensor([[3.5, 2.3, 1.8], [6.6, 5.4, 4.1]], dtype=torch.float64)
print(newTensor)

tensor([[3.5000, 2.3000, 1.8000],
        [6.6000, 5.4000, 4.1000]], dtype=torch.float64)


# Scaler operations.

In [39]:
print(myTensor + 2)
print(newTensor - 2)
print(myTensor * 2)
print(newTensor / 2)
print(myTensor ** 2)

tensor([[3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[ 1.5000,  0.3000, -0.2000],
        [ 4.6000,  3.4000,  2.1000]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[1.7500, 1.1500, 0.9000],
        [3.3000, 2.7000, 2.0500]], dtype=torch.float64)
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)


# Two tensor operations.

In [40]:
print(myTensor + newTensor)
print(myTensor - newTensor)
print(myTensor * newTensor)  # element wise
print(myTensor / newTensor)
print(myTensor ** newTensor)

tensor([[ 4.5000,  4.3000,  4.8000],
        [10.6000, 10.4000, 10.1000]], dtype=torch.float64)
tensor([[-2.5000, -0.3000,  1.2000],
        [-2.6000, -0.4000,  1.9000]], dtype=torch.float64)
tensor([[ 3.5000,  4.6000,  5.4000],
        [26.4000, 27.0000, 24.6000]], dtype=torch.float64)
tensor([[0.2857, 0.8696, 1.6667],
        [0.6061, 0.9259, 1.4634]], dtype=torch.float64)
tensor([[1.0000e+00, 4.9246e+00, 7.2247e+00],
        [9.4101e+03, 5.9489e+03, 1.5503e+03]], dtype=torch.float64)


In [41]:
print(torch.sum(myTensor))
print(torch.sum(newTensor, dim=0))  # column wise addition
print(torch.sum(newTensor, dim=1))  # row wise addition

tensor(21., dtype=torch.float64)
tensor([10.1000,  7.7000,  5.9000], dtype=torch.float64)
tensor([ 7.6000, 16.1000], dtype=torch.float64)


In [43]:
print(torch.mean(newTensor))
print(torch.median(newTensor))


tensor(3.9500, dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)


In [44]:
print(torch.std(newTensor))
print(torch.var(newTensor))

tensor(1.8273, dtype=torch.float64)
tensor(3.3390, dtype=torch.float64)


In [45]:
print(torch.min(newTensor))
print(torch.max(newTensor))
print(torch.argmin(newTensor))
print(torch.argmax(newTensor))

tensor(1.8000, dtype=torch.float64)
tensor(6.6000, dtype=torch.float64)
tensor(2)
tensor(3)


In [46]:
# dot product / matrix multiplication
vec1 = torch.tensor([1, 2])
vec2 = torch.tensor([3, 4])
print(torch.dot(vec1, vec2))

ten1 = torch.rand(2, 3, dtype=torch.float64)
ten2 = torch.rand(3, 2, dtype=torch.float64)
print(torch.matmul(ten1, ten2))

tensor(11)
tensor([[0.6771, 0.8894],
        [0.5151, 0.2827]], dtype=torch.float64)


In [49]:
# cloning of tensors
a = torch.rand(2, 3)

In [50]:
b = a   # initialized same value of tensor as well as memory
b

tensor([[0.7868, 0.7524, 0.7954],
        [0.6311, 0.0499, 0.4145]])

In [51]:
id(a), id(b)

(137972582474816, 137972582474816)

In [52]:
b = a.clone()   # creates copy of same value of tensor as well as new memory allocation

In [53]:
id(a), id(b)

(137972582474816, 137972582551616)

In [54]:
# creating tensors in vRAM / GPUs
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [55]:
torch.rand((3, 6), device=device)

tensor([[0.2375, 0.6731, 0.4295, 0.1510, 0.3218, 0.1745],
        [0.9955, 0.5772, 0.7530, 0.7746, 0.5534, 0.8495],
        [0.8957, 0.5975, 0.0137, 0.1353, 0.4340, 0.1941]], device='cuda:0')

In [59]:
# existing tensor to GPU
newTensor.to(device)

tensor([[3.5000, 2.3000, 1.8000],
        [6.6000, 5.4000, 4.1000]], device='cuda:0', dtype=torch.float64)