In [1]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
tokenizer = Tokenizer(oov_token='nothing')

In [4]:
docs = [
    "I love machine learning",
    "The cat is sleeping on the sofa",
    "She drinks coffee every morning",
    "He went to the market yesterday",
    "Birds are flying in the blue sky",
    "The weather is pleasant today",
    "Raj is studying deep learning at college",
    "Artificial intelligence is changing the world",
    "The movie was interesting but the ending was unexpected",
    "If it rains tomorrow we will stay home and watch movies"
]

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index

{'nothing': 1,
 'the': 2,
 'is': 3,
 'learning': 4,
 'was': 5,
 'i': 6,
 'love': 7,
 'machine': 8,
 'cat': 9,
 'sleeping': 10,
 'on': 11,
 'sofa': 12,
 'she': 13,
 'drinks': 14,
 'coffee': 15,
 'every': 16,
 'morning': 17,
 'he': 18,
 'went': 19,
 'to': 20,
 'market': 21,
 'yesterday': 22,
 'birds': 23,
 'are': 24,
 'flying': 25,
 'in': 26,
 'blue': 27,
 'sky': 28,
 'weather': 29,
 'pleasant': 30,
 'today': 31,
 'raj': 32,
 'studying': 33,
 'deep': 34,
 'at': 35,
 'college': 36,
 'artificial': 37,
 'intelligence': 38,
 'changing': 39,
 'world': 40,
 'movie': 41,
 'interesting': 42,
 'but': 43,
 'ending': 44,
 'unexpected': 45,
 'if': 46,
 'it': 47,
 'rains': 48,
 'tomorrow': 49,
 'we': 50,
 'will': 51,
 'stay': 52,
 'home': 53,
 'and': 54,
 'watch': 55,
 'movies': 56}

In [7]:
tokenizer.word_counts

OrderedDict([('i', 1),
             ('love', 1),
             ('machine', 1),
             ('learning', 2),
             ('the', 8),
             ('cat', 1),
             ('is', 4),
             ('sleeping', 1),
             ('on', 1),
             ('sofa', 1),
             ('she', 1),
             ('drinks', 1),
             ('coffee', 1),
             ('every', 1),
             ('morning', 1),
             ('he', 1),
             ('went', 1),
             ('to', 1),
             ('market', 1),
             ('yesterday', 1),
             ('birds', 1),
             ('are', 1),
             ('flying', 1),
             ('in', 1),
             ('blue', 1),
             ('sky', 1),
             ('weather', 1),
             ('pleasant', 1),
             ('today', 1),
             ('raj', 1),
             ('studying', 1),
             ('deep', 1),
             ('at', 1),
             ('college', 1),
             ('artificial', 1),
             ('intelligence', 1),
             ('changing', 1

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
print(sequences)

[[6, 7, 8, 4], [2, 9, 3, 10, 11, 2, 12], [13, 14, 15, 16, 17], [18, 19, 20, 2, 21, 22], [23, 24, 25, 26, 2, 27, 28], [2, 29, 3, 30, 31], [32, 3, 33, 34, 4, 35, 36], [37, 38, 3, 39, 2, 40], [2, 41, 5, 42, 43, 2, 44, 5, 45], [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]]


In [9]:
from tensorflow.keras.utils import pad_sequences
seq_tf = pad_sequences(sequences, padding='post')

In [10]:
print(seq_tf)
print(seq_tf.shape)

[[ 6  7  8  4  0  0  0  0  0  0  0]
 [ 2  9  3 10 11  2 12  0  0  0  0]
 [13 14 15 16 17  0  0  0  0  0  0]
 [18 19 20  2 21 22  0  0  0  0  0]
 [23 24 25 26  2 27 28  0  0  0  0]
 [ 2 29  3 30 31  0  0  0  0  0  0]
 [32  3 33 34  4 35 36  0  0  0  0]
 [37 38  3 39  2 40  0  0  0  0  0]
 [ 2 41  5 42 43  2 44  5 45  0  0]
 [46 47 48 49 50 51 52 53 54 55 56]]
(10, 11)


## Using pytorch - manually

In [11]:
# Step 1: Build vocabulary
vocab = {"nothing": 0}

for sentence in docs:
    for word in sentence.lower().split():
        if word not in vocab:
            vocab[word] = len(vocab)

print(vocab)

{'nothing': 0, 'i': 1, 'love': 2, 'machine': 3, 'learning': 4, 'the': 5, 'cat': 6, 'is': 7, 'sleeping': 8, 'on': 9, 'sofa': 10, 'she': 11, 'drinks': 12, 'coffee': 13, 'every': 14, 'morning': 15, 'he': 16, 'went': 17, 'to': 18, 'market': 19, 'yesterday': 20, 'birds': 21, 'are': 22, 'flying': 23, 'in': 24, 'blue': 25, 'sky': 26, 'weather': 27, 'pleasant': 28, 'today': 29, 'raj': 30, 'studying': 31, 'deep': 32, 'at': 33, 'college': 34, 'artificial': 35, 'intelligence': 36, 'changing': 37, 'world': 38, 'movie': 39, 'was': 40, 'interesting': 41, 'but': 42, 'ending': 43, 'unexpected': 44, 'if': 45, 'it': 46, 'rains': 47, 'tomorrow': 48, 'we': 49, 'will': 50, 'stay': 51, 'home': 52, 'and': 53, 'watch': 54, 'movies': 55}


In [12]:
# step 2: convert sentence into sequence
sequences = []

for sentence in docs:
    seq = [vocab[word] for word in sentence.lower().split()]
    sequences.append(seq)

print(sequences)

[[1, 2, 3, 4], [5, 6, 7, 8, 9, 5, 10], [11, 12, 13, 14, 15], [16, 17, 18, 5, 19, 20], [21, 22, 23, 24, 5, 25, 26], [5, 27, 7, 28, 29], [30, 7, 31, 32, 4, 33, 34], [35, 36, 7, 37, 5, 38], [5, 39, 40, 41, 42, 5, 43, 40, 44], [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]]


In [13]:
import torch
from torch.nn.utils.rnn import pad_sequence

tensor_sequences = [torch.tensor(seq) for seq in sequences]

padded = pad_sequence(
    tensor_sequences,
    batch_first=True,
    padding_value=vocab["nothing"]
)

print(padded)
print(padded.shape)

tensor([[ 1,  2,  3,  4,  0,  0,  0,  0,  0,  0,  0],
        [ 5,  6,  7,  8,  9,  5, 10,  0,  0,  0,  0],
        [11, 12, 13, 14, 15,  0,  0,  0,  0,  0,  0],
        [16, 17, 18,  5, 19, 20,  0,  0,  0,  0,  0],
        [21, 22, 23, 24,  5, 25, 26,  0,  0,  0,  0],
        [ 5, 27,  7, 28, 29,  0,  0,  0,  0,  0,  0],
        [30,  7, 31, 32,  4, 33, 34,  0,  0,  0,  0],
        [35, 36,  7, 37,  5, 38,  0,  0,  0,  0,  0],
        [ 5, 39, 40, 41, 42,  5, 43, 40, 44,  0,  0],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]])
torch.Size([10, 11])


In [ ]:
tensor_sequences

[tensor([1, 2, 3, 4], device='cuda:0'),
 tensor([ 5,  6,  7,  8,  9,  5, 10], device='cuda:0'),
 tensor([11, 12, 13, 14, 15], device='cuda:0'),
 tensor([16, 17, 18,  5, 19, 20], device='cuda:0'),
 tensor([21, 22, 23, 24,  5, 25, 26], device='cuda:0'),
 tensor([ 5, 27,  7, 28, 29], device='cuda:0'),
 tensor([30,  7, 31, 32,  4, 33, 34], device='cuda:0'),
 tensor([35, 36,  7, 37,  5, 38], device='cuda:0'),
 tensor([ 5, 39, 40, 41, 42,  5, 43, 40, 44], device='cuda:0'),
 tensor([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55], device='cuda:0')]