# Text Representation / Vectorization
> converting raw text into numerical vectors before it can be used for training or prediction.
- One Hot Encoding
- Bag of Words
- TF-IDF
- Word2Vec

In [ ]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array([["I"], ["love"], ["NLP"], ["AI"]])

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(words)

print(encoded)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [ ]:
# Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love NLP",
    "I love AI"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['ai' 'love' 'nlp']
[[0 1 1]
 [1 1 0]]


In [ ]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "people watch campusx",
    "campusx watch campusx",
    "people write comment",
    "campusx write comment"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['campusx' 'comment' 'people' 'watch' 'write']
[[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.8508161  0.         0.         0.52546357 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]


In [ ]:
# Word2Vec
from gensim.models import Word2Vec

# Sample corpus (already tokenized)
sentences = [
    ["i", "love", "machine", "learning"],
    ["machine", "learning", "is", "fun"],
    ["word2vec", "creates", "word", "embeddings"],
    ["deep", "learning", "uses", "embeddings"],
    ["i", "love", "deep", "learning"]
]

# Train Word2Vec model - CBoW
cBoW_model = Word2Vec(
    sentences=sentences,
    vector_size=100,   # Embedding dimension
    window=3,          # Context window size
    sg=0,              # 0 = CBOW
    epochs=10
)


In [ ]:
# skip-gram
skipGram_model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=1,
    sg=1,          # Skip-Gram
    epochs=10
)

In [ ]:
# Save model
# model.save("word2vec.model")

In [ ]:
# get word vector
vector = CBoW_model.wv["learning"]

print(vector)
print("Vector length:", len(vector))

In [ ]:
# get vocab
print(CBoW_)model.wv.index_to_key)

In [ ]:
# get similar words
similar_words = CBoW_model.wv.most_similar("learning", topn=5)

for word, score in similar_words:
    print(word, score)

In [ ]:
# similarity between two words
score = CBoW_model.wv.similarity("machine", "learning")
print(score)